# Generated by Django 5.1.6 on 2025-07-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchlike',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='researchlike',
            name='user',
        ),
        migrations.RenameField(
            model_name='researchpaper',
            old_name='pdf_file',
            new_name='pdf',
        ),
        migrations.RenameField(
            model_name='researchpaper',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='researchpaper',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='allow_download',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='authors',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='category',
            field=models.CharField(choices=[('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('cs', 'Computer Science'), ('bio', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('math', 'Mathematics'), ('engineering', 'Engineering'), ('medicine', 'Medicine'), ('psychology', 'Psychology')], default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ResearchComment',
        ),
        migrations.DeleteModel(
            name='ResearchLike',
        ),
    ]
